[[redirects]]
from = "/home"
to = "/"
status = 301

[[redirects]]
from = "/ecommerce"
to = "./src/pages/PageNotFound.js"
status = 404

[[redirects]]
from = "/pass-through"
to = "/index.html"
status = 200